default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default
  database: sistema_mensagem_app_development

test:
  <<: *default
  database: sistema_mensagem_app_test

production:
  <<: *default
  database: sistema_mensagem_app_production
  username: sistema_mensagem_app
  password: <%= ENV["SISTEMA_MENSAGEM_APP_DATABASE_PASSWORD"] %>
